version: '3.8'

services:
  analytics-pro:
    build: ./backend
    container_name: walmart-analytics
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - FLASK_ENV=development
    restart: always
